CREATE DATABASE KMS_DB
SELECT * FROM KMS_SQL

----WHICH PRODUCT CATEGORY HAD THE HIGHEST SALES ?-----
SELECT TOP 1 [PRODUCT_CATEGORY],
COUNT ([PRODUCT_CATEGORY]) AS SALES
FROM KMS_SQL
GROUP BY PRODUCT_CATEGORY
ORDER BY SALES
DESC


----WHAT ARE THE TOP THREE AND BOTTOM THREE REGIONS IN TERMS OF SALES
SELECT TOP 3 [REGION],
SUM ([SALES]) AS [TOTAL_SALES]
FROM KMS_SQL
GROUP BY REGION
ORDER BY [TOTAL_SALES]
DESC

SELECT TOP 3 [REGION],
SUM ([SALES]) AS [TOTAL_SALES]
FROM KMS_SQL
GROUP BY REGION
ORDER BY [TOTAL_SALES]
ASC

----WHAT WERE THE TOTAL SALES OF APPLIANCES IN ONTARIO?----
SELECT [REGION],
SUM ([SALES]) AS [TOTAL_SALES]
FROM KMS_SQL
WHERE REGION = 'ONTARIO'
GROUP BY [REGION]

----ADVICE THE MANAGEMENT OF KMS ON WHAT TO DO TO INCREASE 
----THE REVENUE FROM THE BOTTOM 10 CUSTOMER----
SELECT TOP 10 [CUSTOMER_NAME],
SUM ([SALES]) AS [TOTAL_SALES]
FROM KMS_SQL
GROUP BY [CUSTOMER_NAME]
ORDER BY [TOTAL_SALES]
ASC

----KMS INCURRED THE MOST SHIPPING COST USING WHICH SHIPPING METHOD?----
SELECT TOP 1 [SHIP_MODE],
SUM ([SHIPPING_COST]) AS [TOTAL SHIPPING COST]
FROM KMS_SQL
GROUP BY [SHIP_MODE]
ORDER BY [TOTAL SHIPPING COST]
DESC

---WHO ARE THE MOST VALUABLE CUSTOMERS AND WHAT PRODUCTS OR SERVICES DO THEY TYPICALLY PURCHASE?----
SELECT [CUSTOMER_NAME], [PRODUCT_NAME],
SUM (SALES) AS [TOTAL SALES]
FROM KMS_SQL
GROUP BY [CUSTOMER_NAME], [PRODUCT_NAME]
ORDER BY [TOTAL SALES]
DESC

----WHICH SMALL BUSINESS CUSTOMER HAD THE HIGHEST SALES?....
SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT,
SUM ([SALES]) AS [TOTAL SALES]
FROM KMS_SQL
WHERE CUSTOMER_SEGMENT = 'SMALL BUSINESS'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY [TOTAL SALES]
DESC

----WHICH CORPORATE CUSTOMER PLACED THE MOST NUMBER OF ORDERS IN 2009-2012?----
SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT, 
COUNT ([ORDER_ID]) AS [ORDER_QUANTITY]
FROM KMS_SQL
WHERE CUSTOMER_SEGMENT = 'CORPORATE' AND ORDER_DATE BETWEEN '2009' AND '2012'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY [ORDER_QUANTITY]
DESC

----WHICH CONSUMER CUSTOMER WAS THE MOST PROFITABLE ONE ?----
SELECT TOP 1 CUSTOMER_NAME, CUSTOMER_SEGMENT, 
SUM (PROFIT) AS TOTAL_PROFIT
FROM KMS_SQL
WHERE CUSTOMER_SEGMENT = 'CONSUMER'
GROUP BY CUSTOMER_NAME, CUSTOMER_SEGMENT
ORDER BY [TOTAL_PROFIT]
DESC

----WHICH CUSTOMER RETURNED ITEMS AND WHAT SEGMENTS DO THEY BELONG TO?----
SELECT CUSTOMER_NAME,CUSTOMER_SEGMENT, [STATUS]
FROM KMS_SQL JOIN [DBO].[ORDER_STATUS] 
ON KMS_SQL. ORDER_ID = [DBO].[ORDER_STATUS].[ORDER_ID]

-----IF THE DELIVERY TRUCK IS THE MOST ECONOMICAL BUT THE LOWEST SHIPPING METHOD
----AND EXPRESS AIR IS THE FASTEST BUT THE MOST EXPENSIVE ONE, DO YOU THINK THE COMPANY
----APPROPRIATELY SPENT SHIPPING COSTS BASED ON THE ORDER OF PRIORITY ?
SELECT ORDER_PRIORITY, SHIP_MODE,
COUNT (ORDER_ID) AS [ORDER_COUNT],
SUM (SALES-PROFIT) AS [ESTIMATED SHIPPING COST],
AVG (DATEDIFF (DAY, [ORDER_DATE],[SHIP_DATE])) AS [AVG SHIP DATE]
FROM KMS_SQL
GROUP BY ORDER_PRIORITY, SHIP_MODE
ORDER BY ORDER_PRIORITY, SHIP_MODE
DESC

----NO, KMS COMPANY DID NOT APPROPRIATELY SPEND SHIPPING COSTS BASED ON THE ORDER OF PROORITY.
--ANALYSIS FROM THE TABLE ABOVE SHOWS THAT THEY SPENT MORE USING AIR EXPRESS ON DELIVERABLES OR ITEMS  
--THAT WERE CONSIDERED LOW OR NOT CRIIICAL BASED ON THE ORDER OF PRIORITY----